[build]
  # command = "cd ./apps/functions && npm i && cd ../../ && nx build resume-builder --prod"
  # functions = "./apps/functions"
  # publish = "apps/resume-builder/publish"
  command = "nx build next-resume-builder --prod"
  publish = "dist/apps/next-resume-builder"

[[plugins]]
  package = "@netlify/plugin-nextjs"
